### ISSUE TITLE
Ao abrir a tela de importações de arquivos ponto não está carregando a listagem das importações realizadas

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#10]
Ao abrir a tela de importações de arquivos ponto não está carregando a listagem das importações realizadas.

Ao abrir a tela de importações com um usuário admin é necessário carregar as importações já realizadas.

**Comment by CathulaOliveira** [comment]
Foi implementado a função que lista as importações realizadas, no carregamento da tela.

**Comment by maicongodinho** [comment]
Verificado que está realizando corretamente a implementação. Por esse motivo estou fechando a issue.
