### ISSUE TITLE
Cores de legenda na listagem de pontos do usuário está diferente das cores da tabela

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#11]
As cores das legendas de status de pontos, na tela de ponto do usuário, devem ser exatamente das cores da tabela aonde é listado os pontos.

**Comment by MaiconGodinho** [comment]
Lembrando que foram adicionados novos status e devem ser coloridos também ambos na tabela e legenda.

Os status são: CORRETO, MARCACAO_INCORRETA, DEBITO, CREDITO, JUSTIFICADO, SEM_INFORMACAO, FERIAS, ATESTADO_MEDICO, PONTO_FACULTATIVO, FALTA_JUSTIFICADA, NAO_ADMITIDO, FERIADO.

Para cada status deve ser definido uma cor e deve ser colorido.

**Comment by CathulaOliveira** [comment]
Foi definido uma cor para cada status, assim como a legenda de acordo com os status existentes na folha ponto em questão.

**Comment by maicongodinho** [comment]
**Validado**

_Movido para concluído e fechado a issue_
