### ISSUE TITLE
Ajustar tamanhos de colunas da tabela de apresentação de ponto de acordo com informações

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#17]
Ajustar tamanhos de colunas da tabela de apresentação de ponto de acordo com informações.

Deixar cada coluna com o tamanho necessário apenas para mostrar a informação.

A coluna de observação deve ser maior também pois pode vir informações maiores.

**Comment by MaiconGodinho** [comment]
Corrigir também a apresentação da informação do Dia da Semana pois está apresentando na tabela "object Object". Deixar essa informação correta e apresentar como primeira coluna.

**Comment by CathulaOliveira** [comment]
Foi ajustado o tamanho de cada coluna, apresentada o dia da semana na tabela, e melhorado a apresentação em tela das legendas.

**Comment by maicongodinho** [comment]
**Validado**

_Movido para concluído e fechado a issue_
