### ISSUE TITLE
Otimizar apresentação de informações na tela de ponto do usuário

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#18]
Otimizar informações de Legendas, Jornadas e Totais na tela de Ponto do usuário.

A informações devem ser apresentadas de forma mais amigável na tela.

Design à discutir.

**Comment by CathulaOliveira** [comment]
Foram implementados novos componentes para a apresentação das legendas e jornadas em tela. Também foi criado o método para apresentar o total de saldo de horas.

**Comment by maicongodinho** [comment]
**Validado**

_Movido para concluído e fechado a issue_
