### ISSUE TITLE
O cadastro de usuário deve possibilitar o administrador cadastrar coordenadores

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#19]
- [ ] Adicionar campo check-box "Coordenador"
OBS: Quando informado que ele é coordenador deve alterar o **TIPO** do usuário que está sendo editado para "COORDENADOR".

**Comment by CathulaOliveira** [comment]
A tela editar perfil foi adaptada, permitindo que o administrador edite todas as informações de cada usuário, e também foi implementado o método para cadastrar novos usuários.
