### ISSUE TITLE
Realizar tratamento de horas ao apresentar valores de horas vindo do banco como minutos

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#21]
- [ ] Realizar tratamento de horas ao apresentar valores de horas vindo do banco como minutos

**Comment by maicongodinho** [comment]
Corrigir valores de horas apresentados nas telas pois está sendo apresentado como minutos.

**Comment by CathulaOliveira** [comment]
Foi criado o formatarMinutos. pipe para a tranformação de minutos para horas.

**Comment by maicongodinho** [comment]
**Validado**

_Movido para concluído e fechado a issue_
