### ISSUE TITLE
Adaptação de componente p-Table do primeng na apresentação das informações para o admin

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#22]
Adaptação de componente p-Table do primeng na apresentação das informações para o admin.

Todas as tabelas devem ser construídas com o componente p-table do primeng para manter padrão.

**Comment by CathulaOliveira** [comment]
Foi implementado o componente p-table na tela que lista as importações realizadas pelo admin.

**Comment by maicongodinho** [comment]
**Validado**

_Movido para concluído e fechado issue_
