### ISSUE TITLE
Realizar integração do worklog do JIRA na tela de inserção de justificativa do ponto

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#23]
Realizar integração do worklog do JIRA na tela de inserção de justificativa do ponto

**Comment by CathulaOliveira** [comment]
Mostrado em tela, no campo justificativa, as issues de cada dia. Aguardando do back-end métodos para salvar issues relacionadas a justificativa.

**Comment by maicongodinho** [comment]
**Validado**

_Movido para concluído e fechado a issue_
