### ISSUE TITLE
Alterar componente de inserção de informações de justificativa

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#25]
Alterar componente de inserção de informações de justificativa.

Sugestão: OverlayPanel

**Comment by maicongodinho** [comment]
Verificado que o componente está correto.
Porém ao clicar para exibir a inserção da justificativa abre múltiplos dialogs na tela.
OBS: A quantidade de dialogs que é aberto na tela é a quantidade exata de justificativas habilitadas para serem inseridas no mês de referência.

**Comment by CathulaOliveira** [comment]
O componente estava dentro de uma estrutura de repetição, ao retira-lo de la o bug foi resolvido

**Comment by maicongodinho** [comment]
**Verificado**

_Movido para concluído e fechado a issue_
