### ISSUE TITLE
Possibilitar geração dinâmica de declarações

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#27]
Possibilitar geração dinâmica de declarações

- [ ] Geração dinâmica de declarações;
- [ ] Impressão de declarações;

**Comment by CathulaOliveira** [comment]
Aguardando definição do back end em relação a como os objetos devem ser enviados de volta ao servidor para a gravação de issues relacionadas a justificativas.

**Comment by CathulaOliveira** [comment]
A tela de ponto oferece a opção de justificar os pontos marcados como Débito, Crédito ou Marcação Incorreta, essas justificativas podem ser vinculadas a issues. E serão listadas na tela que gera a declaração, através dessa tela é feita a exportação em arquivo PDF.
