### ISSUE TITLE
Desenvolver cadastro de produtos

### ISSUE THREAD

**Issue by renansuzin** [volkmerrafael/severino#31]
- Desenvolver cadastro de produtos:

Tabela: 
produto

Campos:
id integer primary key
descricao varchar(50) not null

Validações:
Unicidade da descricao;

Métodos:

getProdutoById(Integer id);
getProdutoByDescricao(String descricao);
salvarProduto(Produto produto);
excluirProduto(id produto);
alterarProduto(Produto produto);

**Comment by volkmerrafael** [comment]
Continuidade do projeto em https://github.com/Antbridge/
