### ISSUE TITLE
Desenvolver cadastro de compra de produtos

### ISSUE THREAD

**Issue by renansuzin** [volkmerrafael/severino#32]
Possibilitar o lançamento de compras de produtos.

Tabelas:
compra, compraprodutos

Campos(compra):
id integer primary key
idfornecedor integer fk(fornecedor.id)
idusuario(usuario.id)
data date not null

Validações:
Data <= Data Atual

Campos(compraproduto):
id integer primary key
idproduto integer fk(produtos.id)
idcompra integer fk(compra.id)
quantidade integer not null
valorunitario numeric(5,2) not null
valortotal numeric(5,2)

Validações:
Quantidade > 0
Valor unitário > 0
Valor total > 0

**Comment by volkmerrafael** [comment]
Continuidade do projeto em https://github.com/Antbridge/
