### ISSUE TITLE
Desenvolver cadastro de venda de produtos

### ISSUE THREAD

**Issue by renansuzin** [volkmerrafael/severino#33]
Possibilitar o lançamento de venda de produtos.

Tabelas:
venda, vendaprodutos

Campos(venda):
id integer primary key
idusuario(usuario.id)
data date not null

Validações:
Data <= Data Atual

Campos(vendaproduto):
id integer primary key
idproduto integer fk(produtos.id)
idvenda integer fk(compra.id)
quantidade integer not null
valorunitario numeric(5,2) not null
valortotal numeric(5,2)

Validações:
Quantidade > 0
Valor unitário > 0
Valor total > 0

**Comment by volkmerrafael** [comment]
Continuidade do projeto em https://github.com/Antbridge/
