### ISSUE TITLE
*Front-End* Refatorar tela de login

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#37]
Refatorar tela de login para oferecer melhor experiência ao usuário.

**Comment by maicongodinho** [comment]
É bem vindo a ajuda para criação de um layout intuitivo caso tenha alguns exemplo de telas que possam auxiliar no desenvolvimento.

**Comment by volkmerrafael** [comment]
Continuidade do projeto em https://github.com/Antbridge/
