### ISSUE TITLE
*Front-End* Refatoração da tela de Feedback

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#38]
Melhorar a experiência de usuário na rotina de Feedback.

**Comment by maicongodinho** [comment]
Realizado documentação do problema  e atualização da wiki.

Tempo gasto: 20m

**Comment by maicongodinho** [comment]
É bem vindo a ajuda para criação de um layout intuitivo caso tenha alguns exemplo de telas que possam auxiliar no desenvolvimento.

**Comment by volkmerrafael** [comment]
Continuidade do projeto em https://github.com/Antbridge/
