### ISSUE TITLE
Mostrar totais de horas extras e de débito mensais na tela de Ponto

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#4]
Adicionar abaixo da tabela de pontos dois campos de texto informando o total de horas extras e de débitos mensais (até o momento de dados importados) conforme os pontos importados do mês de referência.

**Tela:** Ponto

**Comment by MaiconGodinho** [comment]
@CathulaOliveira irá dar andamento na issue pois foi pedido urgência na mesma por @volkmerrafael

**Comment by MaiconGodinho** [comment]
Como em conversa com @volkmerrafael deve ser criado os novos objetos: Jornada e ControleHoras. E fazer a apresentação destes valores em tela.
O objeto controle de horas terá as informações de Horas de Débito e Horas Extras.
O objeto jornada terá uma ou mais jornadas vinculadas ao mês de referência.
Ambas consultas devem passar o ano e mês como parâmetro.

**Comment by CathulaOliveira** [comment]
Foi criado os objetos jornada e controle-horas e os services jornada e controle-horas. E feita a apresentação dos valores em tela.

**Comment by MaiconGodinho** [comment]
Verificado que a apresentação da jornada deve suportar a apresentação múltipla de várias jornadas caso ocorra.

Também deve ser apresentado na tabela o índice da legenda da jornada apresentada anteriormente.

**Comment by CathulaOliveira** [comment]
Feito a apresentação de múltiplas jornadas e do índice de cada jornada na tabela

**Comment by maicongodinho** [comment]
**Validado**

_Movido para concluído_
