### ISSUE TITLE
Implementar Feedback

### ISSUE THREAD

**Issue by maicongodinho** [volkmerrafael/severino#9]
Implementar cadastramento de feedback. Deverá ser possibilitado o usuário (admin ou usuário comum) poder enviar feedback sobre a solução via uma tela com campo de texto.

**Comment by CathulaOliveira** [comment]
Foi criado uma tela para o cadastro de feedbacks. O usuário admin tem acesso a uma lista com todos os feedbacks e o usuário comum tem acesso a seus próprios feedbacks.
